# 基本配置
enableImmutableInstalls: false
nodeLinker: node-modules
httpTimeout: 300000

# npm 镜像配置
npmRegistryServer: "https://registry.npmmirror.com"

# 注意：Yarn 4.x 不支持在 .yarnrc.yml 中设置环境变量
# 请使用命令行设置 ELECTRON_MIRROR 环境变量

# Yarn 路径
yarnPath: .yarn/releases/yarn-4.6.0.cjs