name: Tauri Desktop Release Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target universal-apple-darwin'
            target: 'aarch64-apple-darwin,x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
            target: 'x86_64-unknown-linux-gnu'
          - platform: 'windows-latest'
            args: ''
            target: 'x86_64-pc-windows-msvc'

    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add Rust targets (Unix)
        if: matrix.platform != 'windows-latest'
        run: |
          IFS=',' read -ra TARGETS <<< "${{ matrix.target }}"
          for target in "${TARGETS[@]}"; do
            rustup target add "$target"
          done

      - name: Add Rust targets (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          $targets = "${{ matrix.target }}" -split ","
          foreach ($target in $targets) {
            rustup target add $target.Trim()
          }

      - name: Setup Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install Linux Dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libssl-dev \
            libxdo-dev \
            libsoup-3.0-dev \
            libjavascriptcoregtk-4.0-dev \
            libwebkit2gtk-4.1-dev \
            libgtk-4-dev \
            build-essential \
            curl \
            wget \
            file \
            libxcb-shape0-dev \
            libxcb-xfixes0-dev \
            pkg-config

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install Frontend Dependencies
        run: |
          npm ci || {
            echo "npm ci failed, trying alternative approaches..."
            rm -rf node_modules package-lock.json
            npm cache clean --force
            npm install --no-package-lock || npm install --legacy-peer-deps
          }

      - name: Build Frontend
        run: npm run build

      - name: Build Tauri App (Release)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.args }}

      - name: Upload Build Artifacts (Windows)
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-build
          path: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/nsis/*.exe

      - name: Upload Build Artifacts (macOS)
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-release-build
          path: |
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/macos/*.app

      - name: Upload Build Artifacts (Linux)
        if: matrix.platform == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: linux-release-build
          path: |
            src-tauri/target/release/bundle/appimage/*.AppImage
            src-tauri/target/release/bundle/deb/*.deb

  build-summary:
    needs: build-release
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Build Summary
        run: |
          echo "## 🖥️ Tauri Desktop Release Build Complete!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📦 Build Status" >> $GITHUB_STEP_SUMMARY
          echo "| Platform | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Windows | ${{ needs.build-release.result == 'success' && '✅ Success' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| macOS | ${{ needs.build-release.result == 'success' && '✅ Success' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Linux | ${{ needs.build-release.result == 'success' && '✅ Success' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "📦 **Release build artifacts are ready for manual release!**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📥 Download Artifacts" >> $GITHUB_STEP_SUMMARY
          echo "- Go to the **Actions** tab" >> $GITHUB_STEP_SUMMARY
          echo "- Click on this workflow run" >> $GITHUB_STEP_SUMMARY
          echo "- Download the platform-specific build artifacts" >> $GITHUB_STEP_SUMMARY
          echo "- Manually create a release and upload the files" >> $GITHUB_STEP_SUMMARY
