name: Tauri Android Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android,i686-linux-android
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android NDK
        run: |
          echo "Installing Android NDK..."
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "ndk;26.1.10909125"
          echo "ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/26.1.10909125" >> $GITHUB_ENV
          echo "NDK_HOME=$ANDROID_HOME/ndk/26.1.10909125" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci
      
      - name: Build frontend
        run: npm run build
      
      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli@latest
      
      - name: Build Android APK (Release)
        run: |
          cd src-tauri
          tauri android build --apk --split-per-abi
        env:
          ANDROID_NDK_ROOT: ${{ env.ANDROID_NDK_ROOT }}
          NDK_HOME: ${{ env.NDK_HOME }}
      
      - name: Find APK files
        run: |
          echo "Searching for APK files..."
          find src-tauri -name "*.apk" -type f

      - name: Upload All APKs
        uses: actions/upload-artifact@v4
        with:
          name: android-apks-all-architectures
          path: src-tauri/gen/android/app/build/outputs/apk/**/*.apk
