name: Tauri Android Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android,i686-linux-android
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          ndk-version: 26.1.10909125
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build frontend
        run: npm run build
      
      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli@latest
      
      - name: Build Android APK
        run: |
          cd src-tauri
          tauri android build --apk
        env:
          ANDROID_NDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}/ndk/26.1.10909125
      
      - name: Find and Upload APK
        run: |
          echo "Searching for APK files..."
          find src-tauri -name "*.apk" -type f
          APK_PATH=$(find src-tauri -name "*.apk" -type f | head -1)
          if [ -n "$APK_PATH" ]; then
            echo "Found APK: $APK_PATH"
            echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
          else
            echo "No APK found"
            exit 1
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ${{ env.APK_PATH }}
